# AWS CodeBuild buildspec
# By Ramzy


version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - CODEBUILD_RESOLVED_SOURCE_VERSION="${CODEBUILD_RESOLVED_SOURCE_VERSION:-$IMAGE_TAG}"
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-8)
      - IMAGE_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$NAMESPACE-$IMAGE_TAG"
      - export KUBECONFIG=$HOME/.kube/config

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_URI -f Docker/$DOCKERFILE_NAME.Dockerfile  --build-arg API_BASE_URL=$API_BASE_URL  --build-arg REACT_APP_URL=$REACT_APP_URL  --build-arg REACT_APP_LOGIN_URL=$REACT_APP_LOGIN_URL  --build-arg REACT_APP_DOMAIN=$REACT_APP_DOMAIN  --build-arg REACT_APP_SUBDOMAIN=$REACT_APP_SUBDOMAIN --build-arg REACT_APP_DOCUMENTS_URL=$REACT_APP_DOCUMENTS_URL .
  post_build:
    commands:
      - bash -c "if [ /"$CODEBUILD_BUILD_SUCCEEDING/" == /"0/" ]; then exit 1; fi"
      - echo Build stage successfully completed on `date`
      - echo Pushing the Docker image...
      - docker push $IMAGE_URI
      - printf '[{"name":"%s","imageUri":"%s"}]' "$SERVICE_NAME" "$IMAGE_URI" > "$SERVICE_NAME"-images.json
artifacts:
  files:
    - $SERVICE_NAME-images.json
