import * as Yup from 'yup';

export const LoanProduct: any = {
    productName: '',
    calculationFormulaId: '',
    loanNature: 'cash',
    currency: 'egp',
    periodLength: 1,
    periodType: 'days',
    noOfInstallments: 0,
    lateDays: 0,
    gracePeriod: 0,
    interest: 0,
    interestPeriod: 'yearly',
    allowInterestAdjustment: false,
    inAdvanceFees: 0,
    inAdvanceFrom: 'principal',
    inAdvanceType: 'uncut',
    stamps: 0,
    allowStampsAdjustment: true,
    representativeFees: 0,
    allowRepresentativeFeesAdjustment: true,
    adminFees: 0,
    allowAdminFeesAdjustment: true,
    earlyPaymentFees: 0,
    maxNoOfRestructuring: 0,
    minPrincipal: 0,
    maxPrincipal: 0,
    minInstallment: 0,
    maxInstallment: 0,
    applicationFee: 0,
    allowApplicationFeeAdjustment: false,
    spreadApplicationFee: false,
    individualApplicationFee: 0,
    applicationFeePercent: 0,
    applicationFeeType: 'principal',
    applicationFeePercentPerPerson: 0,
    applicationFeePercentPerPersonType: 'principal',
    loanImpactPrincipal: true,
    mustEnterGuarantor: true,
    guarantorGuaranteesMultiple: true,
    deductionFee: 0,
    allocatedDebtForGoodLoans: 0,
    aging: [{ from: 0, to: 1, fee: 0 }, { from: 0, to: 1, fee: 0 }, { from: 0, to: 1, fee: 0 }, { from: 0, to: 1, fee: 0 }, { from: 0, to: 1, fee: 0 }, { from: 0, to: 1, fee: 0 }, { from: 0, to: 1, fee: 0 }],
    mergeUndoubtedLoans: false,
    mergeUndoubtedLoansFees: 0,
    mergeDoubtedLoans: false,
    mergeDoubtedLoansFees: 0,
    pushPayment: 0,
    pushDays: [0, 0, 0, 0, 0, 0, 0],
    pushHolidays: 'previous',
    enabled: true,
    viceFieldManagerAndDate: true,
    reviewerChiefAndDate: true,
    branchManagerAndDate: true,
}
export const LoanProductValidation = Yup.object().shape({
    productName: Yup.string().required('required!'),
    calculationFormulaId: Yup.string().required('required!'),
    periodLength: Yup.number().min(1, "Can't be less than 1").required('required!'),
    noOfInstallments: Yup.number().min(0, "Can't be less than 0").required('required!'),
    lateDays: Yup.number().min(0, "Can't be less than 0").required('required!'),
    gracePeriod: Yup.number().min(0, "Can't be less than 0").required('required!'),
    interest: Yup.number().min(0, "Can't be less than 0").max(100,"Can't be more than 100").required('required!'),
    inAdvanceFees: Yup.number().min(0, "Can't be less than 0").max(100,"Can't be more than 100").required('required!'),
    stamps: Yup.number().min(0, "Can't be less than 0").required('required!'),
    representativeFees: Yup.number().min(0, "Can't be less than 0").required('required!'),
    adminFees: Yup.number().min(0, "Can't be less than 0").required('required!'),
    earlyPaymentFees: Yup.number().min(0, "Can't be less than 0").required('required!'),
    maxNoOfRestructuring: Yup.number().min(0, "Can't be less than 0").required('required!'),
    minPrincipal: Yup.number().min(0, "Can't be less than 0").required('required!'),
    maxPrincipal: Yup.number().min(0, "Can't be less than 0").required('required!'),
    minInstallment: Yup.number().min(0, "Can't be less than 0").required('required!'),
    maxInstallment: Yup.number().min(0, "Can't be less than 0").required('required!'),
    applicationFee: Yup.number().min(0, "Can't be less than 0").required('required!'),
    individualApplicationFee: Yup.number().min(0, "Can't be less than 0").required('required!'),
    applicationFeePercent: Yup.number().min(0, "Can't be less than 0").max(100,"Can't be more than 100").required('required!'),
    applicationFeePercentPerPerson: Yup.number().min(0, "Can't be less than 0").max(100,"Can't be more than 100").required('required!'),
    loanNature: Yup.string().required('required!'),
    currency: Yup.string().required('required!'),
    periodType: Yup.string().required('required!'),
    interestPeriod: Yup.string().required('required!'),
    inAdvanceFrom: Yup.string().required('required!'),
    inAdvanceType: Yup.string().required('required!'),
    applicationFeeType: Yup.string().required('required!'),
    applicationFeePercentPerPersonType: Yup.string().required('required!'),
    pushHolidays: Yup.string().required('required!'),
    allowInterestAdjustment: Yup.boolean().required('required!'),
    allowStampsAdjustment: Yup.boolean().required('required!'),
    allowRepresentativeFeesAdjustment: Yup.boolean().required('required!'),
    allowAdminFeesAdjustment: Yup.boolean().required('required!'),
    allowApplicationFeeAdjustment: Yup.boolean().required('required!'),
    spreadApplicationFee: Yup.boolean().required('required!'),
    loanImpactPrincipal: Yup.boolean().required('required!'),
    mustEnterGuarantor: Yup.boolean().required('required!'),
    guarantorGuaranteesMultiple: Yup.boolean().required('required!'),
})