on: [push]
jobs:
  check-types:
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '12.16.1'
        - run: npm ci
        - run: npm run check-type-mohassel
